app:
  serviceName: "rest-books-api"
  host: "127.0.0.1"
  port: 8000
db:
  name: "books_db"
  schema: "public"
  user: "kevv"
  host: "localhost"
  password: "postgres"
  port: 5432
  logMode: true
  sslMode: "disable"
  migrationPath: "./scripts"
  connectionPool:
    maxOpenConnections: 30
    maxIdleConnections: 10
    maxIdleTime: 30
    maxLifeTime: 3600
    timeout: 30
